language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.12.3
script: bundle exec rspec spec
env:
  global:
    secure: Ru7XMnp+0D3tqXJJKRivQHA/e76dhUS4zv9SAvcyzTeuELtn41PQ07r53lunz2t6btXuyRy5Cyr9DD7CnP+ocXbe7Ce6pl5i5gZ7R5KIeWgxZLtKQ5xNs39Yb1jP7RqpgwQFfM86ByQ65zVBKYIRXmDdVfJoG6GM+TeXz6gi3AHwkRmvzSuS5KQ/61GZ8gr6sD55aR1x/YNBsubR7VmKFOmRGAt8XcUND+ArHiDe4mBolKF8d+jYI7a5csDT6ewD5RyT5HOgi0mKobCntvnLQJ4OnCzLjZfihfaw/Dwdp1Ifr6wdvZDB6JtBCxHncOxQ+0oHWEHhzIWHgN1mSmx5CI08J6Hty1nNNF2rgUUdLjh9sYE51QcGWdtCQY5WdYJ2ttGWNhaNFeJR9LPtE+MN3vUtMh0aroCR4g9hs4aLxpcSbdkTlctkMoGuGV2yuFx4R+8CFkReuZNo2t87MophSXo09eEwFE92Nq1S0DrPOzN+IFAy/XhZKnKWHfA7Oi065HlOZ+N7vOQIEVfxrni1mKLarzqDfPGgR/rbwEq7i1YJqBChZU8WXb6ncnkI/bSpurStgz+2+PdSCFNFSmw/s4CPPeiqNPcXM5Z00GlOXkHJ8PkUnc9AhdKb0tfmeU6jC4CX3r9ScFMwTWFU7MfxcFRZ5z+aeaMM5ejqgkueu10=
